"""add event and registration

Revision ID: 543d99b874b9
Revises: 2a828b531de3
Create Date: 2026-04-08 21:28:11.173632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '543d99b874b9'
down_revision: Union[str, Sequence[str], None] = '2a828b531de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', sa.String(), nullable=False))
    op.add_column('events', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.drop_column('events', 'started_at')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'name')
    op.drop_column('events', 'quota')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'ended_at')
    op.create_index(op.f('ix_registrations_id'), 'registrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrations_id'), table_name='registrations')
    op.add_column('events', sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('quota', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_column('events', 'date')
    op.drop_column('events', 'title')
    # ### end Alembic commands ###
